// v2 样板 30 人的原文来源登记。
// ws = 维基文库页面标题；section = 多人合传时截取传主一段：start 为开头原文，end 可选；wiki = 中文维基条目，只作年表参考，不作引文来源。
export const SAMPLE = [
  { id:"maozedong", name:"毛泽东", wiki:"毛泽东", ws:[{ title:"关于建国以来党的若干历史问题的决议", label:"《关于建国以来党的若干历史问题的决议》" }] },
  { id:"qinst", name:"秦始皇", wiki:"秦始皇", ws:[{ title:"史記/卷006", label:"《史记·秦始皇本纪》" }] },
  { id:"liubang", name:"刘邦", wiki:"刘邦", ws:[{ title:"史記/卷008", label:"《史记·高祖本纪》" }] },
  { id:"xiangyu", name:"项羽", wiki:"项羽", ws:[{ title:"史記/卷007", label:"《史记·项羽本纪》" }] },
  { id:"hanxin", name:"韩信", wiki:"韩信", ws:[{ title:"史記/卷092", label:"《史记·淮阴侯列传》" }] },
  { id:"caocao", name:"曹操", wiki:"曹操", ws:[{ title:"三國志/卷01", label:"《三国志·魏书·武帝纪》" }] },
  { id:"zhugeliang", name:"诸葛亮", wiki:"诸葛亮", ws:[{ title:"三國志/卷35", label:"《三国志·蜀书·诸葛亮传》" }] },
  { id:"lshimin", name:"李世民", wiki:"唐太宗", ws:[{ title:"舊唐書/卷2", label:"《旧唐书·太宗本纪上》" }, { title:"舊唐書/卷3", label:"《旧唐书·太宗本纪下》" }] },
  { id:"wanganshi", name:"王安石", wiki:"王安石", ws:[{ title:"宋史/卷327", label:"《宋史·王安石传》", section:{ start:"王安石，字介甫" } }] },
  { id:"yuefei", name:"岳飞", wiki:"岳飞", ws:[{ title:"宋史/卷365", label:"《宋史·岳飞传》", section:{ start:"岳飛字鵬舉" } }] },
  { id:"zhuyuanzhang", name:"朱元璋", wiki:"明太祖", ws:[{ title:"明史/卷1", label:"《明史·太祖本纪一》" }, { title:"明史/卷2", label:"《明史·太祖本纪二》" }, { title:"明史/卷3", label:"《明史·太祖本纪三》" }] },
  { id:"zhangjuzheng", name:"张居正", wiki:"张居正", ws:[{ title:"明史/卷213", label:"《明史·张居正传》", section:{ start:"張居正，字叔大" } }] },
  { id:"confucius", name:"孔子", wiki:"孔子", ws:[{ title:"史記/卷047", label:"《史记·孔子世家》" }] },
  { id:"libai", name:"李白", wiki:"李白", ws:[{ title:"舊唐書/卷190下", label:"《旧唐书·文苑传下·李白》", section:{ start:"李白字太白" } }, { title:"新唐書/卷202", label:"《新唐书·文艺传中·李白》", section:{ start:"李白，字太白" } }] },
  { id:"dufu", name:"杜甫", wiki:"杜甫", ws:[{ title:"舊唐書/卷190下", label:"《旧唐书·文苑传下·杜甫》", section:{ start:"杜甫，字子美" } }, { title:"新唐書/卷201", label:"《新唐书·文艺传上·杜甫》", section:{ start:"甫，字子美", end:"【王勃】" } }] },
  { id:"sushi", name:"苏轼", wiki:"苏轼", ws:[{ title:"宋史/卷338", label:"《宋史·苏轼传》", section:{ start:"蘇軾，字子瞻" } }] },
  { id:"guanzhong", name:"管仲", wiki:"管仲", ws:[{ title:"史記/卷062", label:"《史记·管晏列传》", section:{ start:"管仲夷吾者", end:"晏平仲" } }] },
  { id:"shangyang", name:"商鞅", wiki:"商鞅", ws:[{ title:"史記/卷068", label:"《史记·商君列传》" }] },
  { id:"hanwudi", name:"汉武帝", wiki:"汉武帝", ws:[{ title:"漢書/卷006", label:"《汉书·武帝纪》" }] },
  { id:"simqian", name:"司马迁", wiki:"司马迁", ws:[{ title:"漢書/卷062", label:"《汉书·司马迁传》" }] },
  { id:"zhangheng", name:"张衡", wiki:"张衡", ws:[{ title:"後漢書/卷59", label:"《后汉书·张衡传》" }] },
  { id:"wuzetian", name:"武则天", wiki:"武则天", ws:[{ title:"舊唐書/卷6", label:"《旧唐书·则天皇后本纪》" }] },
  { id:"xuanzang", name:"玄奘", wiki:"玄奘", ws:[{ title:"舊唐書/卷191", label:"《旧唐书·方伎传·玄奘》", section:{ start:"僧玄奘" } }] },
  { id:"fanzhongyan", name:"范仲淹", wiki:"范仲淹", ws:[{ title:"宋史/卷314", label:"《宋史·范仲淹传》", section:{ start:"范仲淹字希文" } }] },
  { id:"liqzhao", name:"李清照", wiki:"李清照", ws:[{ title:"宋史/卷444", label:"《宋史·文苑传·李格非（附李清照）》", section:{ start:"李格非，字文叔" } }] },
  { id:"wentianxiang", name:"文天祥", wiki:"文天祥", ws:[{ title:"宋史/卷418", label:"《宋史·文天祥传》", section:{ start:"文天祥，字宋瑞" } }] },
  { id:"temujin", name:"成吉思汗", wiki:"成吉思汗", ws:[{ title:"元史/卷001", label:"《元史·太祖本纪》" }] },
  { id:"wangyangming", name:"王阳明", wiki:"王守仁", ws:[{ title:"明史/卷195", label:"《明史·王守仁传》", section:{ start:"王守仁，字伯安" } }] },
  { id:"kangxi", name:"康熙", wiki:"康熙帝", ws:[{ title:"清史稿/卷6", label:"《清史稿·圣祖本纪一》" }, { title:"清史稿/卷7", label:"《清史稿·圣祖本纪二》" }, { title:"清史稿/卷8", label:"《清史稿·圣祖本纪三》" }] },
  { id:"linzexu", name:"林则徐", wiki:"林则徐", ws:[{ title:"清史稿/卷369", label:"《清史稿·林则徐传》", section:{ start:"林則徐，字少穆" } }] },
];
